apiVersion: v1
kind: Secret
metadata:
  name: awx-postgres-configuration
  namespace: apps
stringData:
  host: postgres-service.apps.svc.cluster.local
  port: "5432"
  database: awx
  username: awx
  password: awxpassword
  sslmode: prefer
  type: unmanaged
type: Opaque
