apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: apps
resources:
  - authentik-deployment.yaml
  - authentik-pvc.yaml
  - authentik-configmap.yaml
  - authentik-secrets.secret.enc.yaml
