apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: apps
resources:
  - docker-mcp-gateway-deployment.yaml
  - docker-mcp-gateway-service.yaml
  - docker-mcp-gateway-pvc.yaml
  - docker-mcp-gateway-configmap.yaml
  - ingress.yaml
