apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - postgres-secret.yaml
  - postgres-manifest.yaml
  - postgres-pvc.yaml
  - postgres-backup-pvc.yaml
  - postgres-backup-cronjob.yaml
  - postgres-init-scripts.yaml