# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: apps
resources:
  - n8n-pv.yaml
  - n8n-pvc.yaml
  - n8n-configmap.yaml
  - n8n-deployment.yaml
  - n8n-service.yaml
  - n8n-ingress.yaml
  - n8n-groupme-workflows.yaml
  - n8n-langchain-rag-workflow.yaml
