apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: apps
resources:
  - freshrss-pvc.yaml
  - freshrss-configmap.yaml
  - freshrss-deployment.yaml
  - freshrss-service.yaml
  - freshrss-ingress.yaml
