apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: zionup-production
resources:
  - namespace.yaml
  - zionup-configmap.yaml
  - zionup-secrets.yaml
  - postgres-deployment.yaml
  - redis-deployment.yaml
  - backend-deployment.yaml
  - frontend-deployment.yaml
  - media-pvc.yaml
  - ingress.yaml
