apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./apps-namespace.yaml
  - ./sources
#  - ./kubernetes-dashboard  # Disabled - using Homepage and Grafana instead
  - ./metallb-system
  - ./ingress-nginx
  - ./local-storage
  - ./nfs-storage
  - ./prometheus
  - ./grafana
  - ./plex
  - ./homepage
  - ./metrics-server
  - ./n8n
  - ./postgres
  - ./pihole
  - ./jenkins
  - ./loki
  - ./redis
  - ./mcp-servers
  - ./openwebui
  - ./pgadmin
  - ./llamafactory
  - ./uptime-kuma
  - ./authentik
  - ./freshrss


