apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - pgadmin-deployment.yaml
  - ingress.yaml
# Note: pgadmin-credentials secret must be created manually via kubectl
# See README.md for instructions
