apiVersion: v1
kind: ConfigMap
metadata:
  name: pgadmin-config
  namespace: apps
data:
  servers.json: |
    {
      "Servers": {
        "1": {
          "Name": "Homelab Postgres",
          "Group": "Servers",
          "Host": "postgres-service.apps.svc.cluster.local",
          "Port": 5432,
          "MaintenanceDB": "postgres",
          "Username": "postgres",
          "SSLMode": "prefer"
        }
      }
    }
