apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-server
  namespace: apps
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  volumeName: prometheus-local-pv
  resources:
    requests:
      storage: 45Gi
